core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('swapi.urls'), name='swapi')
]

swapi/urls.py
from django.urls import path
from .views import get_collection, CollectionListView, CollectionDetailView

app_name = "collections"


urlpatterns = [
    path('upload/collection/', get_collection, name='upload'),
    path('collections/', CollectionListView.as_view(), name='list'),
    path('collections/<int:pk>/', CollectionDetailView.as_view(), name="detail"),

]

swapi/models.py
from django.db import models


class CsvFile(models.Model):
    """CSV file model"""

    filename = models.CharField(max_length=100)
    upload = models.FileField(upload_to='uploads/', blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-creation_date']

    def __str__(self):
        return f'{self.creation_date} - {self.filename}'

swapi/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import redirect
from django.core.files.base import ContentFile
from .models import CsvFile
import requests
import uuid
import csv
import pandas


SWAPI_PEOPLE = 'https://swapi.dev/api/people/'


class CollectionListView(ListView):

    model = CsvFile
    template_name = "collections.html"
    context_object_name = 'collections'


class CollectionDetailView(DetailView):

    model = CsvFile
    template_name = "collection.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        file = pandas.read_csv(f'media/uploads/{self.object.filename}')
        result = {}
        i = 1
        for index, row in file.iterrows():
            result.update({i: row.to_dict()})
            i += 1
        context['collections'] = result
        return context


def get_collection(request):
    filename = f'{uuid.uuid4()}.csv'
    file = CsvFile.objects.create(filename=filename)
    file.upload.save(filename, ContentFile(''))

    response = requests.get(SWAPI_PEOPLE).json()

    with open(f'media/uploads/{filename}', mode='w') as file:

        data_writer = csv.writer(file)
        column = [['name', 'height', 'mass', 'hair_color', 'skin_color', 'eye_color', 'birth_year',
                   'gender', 'homeworld', 'date']]
        data_writer.writerows(column)

        for row in response['results']:
            homeworld = requests.get(row['homeworld']).json()

            data_writer.writerow(
                [row['name'], row['height'], row['mass'], row['hair_color'], row['skin_color'], row['eye_color'],
                 row['birth_year'],
                 row['gender'], homeworld['name'], row['edited'][:10]])

    return redirect('collections:list')

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>
<style>
</style>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FFD700">
        <a class="navbar-brand" href=""><b>Star Wars</b> Explorer</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'collections:list'%}" style="color: cornflowerblue">Collections</a>
      </li>
    </ul>
  </div>
</nav>
{% block content %}

{% endblock content %}

templates/collection.html
{% extends 'base.html' %}
{% block title %}Collections{% endblock title %}
{% block content %}

    <div style="margin-top: 5%; margin-left: 5%">
        <h2>{{ collection.filename }}</h2>
    </div>
    <div>
        <table class="table table-bordered" , style="width: 1700px; margin-left: 5%">
            <thead>
            <tr>
                <th>name</th>
                <th>height</th>
                <th>mass</th>
                <th>hair_color</th>
                <th>skin_color</th>
                <th>eye_color</th>
                <th>birth_year</th>
                <th>gender</th>
                <th>homeworld</th>
                <th>date</th>
            <tr>
            </thead>
            {% for key, value in collections.items %}
                <tr>
                    <td>{{ value.name }}</td>
                    <td>{{ value.height }}</td>
                    <td>{{ value.mass }}</td>
                    <td>{{ value.hair_color }}</td>
                    <td>{{ value.skin_color }}</td>
                    <td>{{ value.eye_color }}</td>
                    <td>{{ value.birth_year }}</td>
                    <td>{{ value.gender }}</td>
                    <td>{{ value.homeworld }}</td>
                    <td>{{ value.date }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/collections.html
{% extends 'base.html' %}
{% block title %}Collections{% endblock title %}
{% block content %}

    <div style="margin-top: 5%; margin-left: 5%">
        <h1>Collections<a href="{% url 'collections:upload' %}"
                          class="btn btn-secondary btn-lg active"
                          role="button" aria-pressed="true"
                          style="background-color: forestgreen;
                      margin-left: 1%">Fetch</a></h1>
    </div>

    <table class="table table-bordered" style="width: 1700px; margin-left: 5%">
        <thead>
        {% for collection in collections %}
            <tr>
                <th scope="col"><a style="color: dodgerblue"
                                   href="{% url 'collections:detail' collection.id %}">{{ collection.creation_date }}</a>
                </th>
            </tr>
            </thead>
        {% endfor %}
    </table>
{% endblock content %}